description: FileWave MDM Servers Infrastructure Load Balanced
maintainers:
- name: Matteo Ruello
icon: https://raw.githubusercontent.com/fw-dev/k8s-helm-charts/master/fw/filewave_icon.png
name: fwserver-single
version: 1.0.0