apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.appscode.com/type: LoadBalancer
    # ingress.appscode.com/ssl-passthrough: "true"
spec:
  tls:
  - secretName: default-cert
    hosts:
    {{- range .Values.servers }}
      - {{ .host }}
    {{- end }} 
  rules:
{{- range .Values.servers }}
  - host: {{ .host }}
    tcp:
      port: 443
      noTLS: true
      # paths:
        # - backend:
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: fw-web
  - host: {{ .host }}
    tcp:
      port: 20443
      noTLS: true
      # paths:
      #   - backend:
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: mdm
  - host: {{ .host }}
    tcp:
      port: 20445
      noTLS: true
      # paths:
      #   - backend:
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: django
  - host: {{ .host }}
    tcp:
      port: 20446
      noTLS: true
      # paths:
      #   - backend:
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: noidea
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}05
      noTLS: true
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: port20005
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}06
      noTLS: true
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: port20006
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}16
      noTLS: true
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: fwxserver-a
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}17
      noTLS: true
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: fwserver-ssl
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}15
      noTLS: true
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: fwsxerver-s
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}13
      noTLS: true
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: booster
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}30
      noTLS: true
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: vnc-relay
  
{{- end }}
