apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    ingress.appscode.com/type: LoadBalancer
spec:
  tls:
  - secretName: default-cert
    hosts:
    {{- range .Values.servers }}
      - {{ .host }}
    {{- end }} 
  rules:
{{- range .Values.servers }}
  - host: {{ .host }}
    http:
      port: 443
      paths:
        - backend:
            serviceName: fwserver-svc-{{ .name }}
            servicePort: fw-web
  - host: {{ .host }}
    http:
      port: 20443
      paths:
        - backend:
            serviceName: fwserver-svc-{{ .name }}
            servicePort: mdm
  - host: {{ .host }}
    http:
      port: 20445
      paths:
        - backend:
            serviceName: fwserver-svc-{{ .name }}
            servicePort: django
  - host: {{ .host }}
    http:
      port: 20446
      paths:
        - backend:
            serviceName: fwserver-svc-{{ .name }}
            servicePort: noidea
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}05
      noTLS: true
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: port20005
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}06
      noTLS: true
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: port20006
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}16
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: fwxserver-a
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}17
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: fwserver-ssl
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}15
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: fwsxerver-s
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}13
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: booster
  - host: {{ .host }}
    tcp:
      port: {{ .port_prefix }}30
      backend:
        serviceName: fwserver-svc-{{ .name }}
        servicePort: vnc-relay
  
{{- end }}
