{{- $storage := .Values.storageClassName }}
{{- range .Values.servers }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fwserver-standard-{{ .name }}
  labels:
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .storageSpaceGi }}Gi
  storageClassName: {{ $storage }}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fwserver-ssd-{{ .name }}
  labels:
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .storageSpaceGi }}Gi
  storageClassName: {{ $storage }}
{{- end}}
