{{- range .Values.servers }}
---
kind: Service
apiVersion: v1
metadata:
  name: fwserver-svc-{{ .name }}
  annotations:
      ingress.appscode.com/backend-tls: ssl verify none
spec:
  type: NodePort
  ports:
  - name: fw-web
    port: 443
    protocol: TCP

  - name: mdm
    protocol: TCP
    port: 20443
    
  - name: django
    protocol: TCP
    port: 20445

  - name: noidea
    protocol: TCP
    port: 20446
    
  - name: booster
    port: {{ .port_prefix }}3
    targetPort: 20013
    protocol: TCP
   
  - name: port20005
    protocol: TCP
    port: {{ .port_prefix }}8
    targetPort: 20005
    
  - name: port20006
    protocol: TCP
    port: {{ .port_prefix }}9
    targetPort: 20006
    
  - name: fwxserver-s
    protocol: TCP
    port: {{ .port_prefix }}5
    targetPort: 20015
    
  - name: fwxserver-a 
    protocol: TCP
    port: {{ .port_prefix }}6
    targetPort: 20016
    
  - name: fwserver-ssl
    protocol: TCP
    port: {{ .port_prefix }}7
    targetPort: 20017

  selector:
    app: fwserver-{{ .name }}
{{- end}}

