{{- range .Values.servers }}
---
kind: Service
apiVersion: v1
metadata:
  name: fwserver-svc-tcp-{{ .name }}
  annotations:
    # ingress.appscode.com/backend-tls: ssl verify none
    # ingress.appscode.com/ssl-passthrough: "true"
spec:
  type: NodePort
  ports:
   
  - name: port20005
    protocol: TCP
    port: {{ .port_prefix }}05
    targetPort: 20005
    
  - name: port20006
    protocol: TCP
    port: {{ .port_prefix }}06
    targetPort: 20006
    
  - name: fwxserver-s
    protocol: TCP
    port: {{ .port_prefix }}15
    targetPort: 20015
    
  - name: fwxserver-a 
    protocol: TCP
    port: {{ .port_prefix }}16
    targetPort: 20016
    
  - name: fwserver-ssl
    protocol: TCP
    port: {{ .port_prefix }}17
    targetPort: 20017

  - name: vnc-relay
    protocol: TCP
    port: {{ .port_prefix }}30
    targetPort: {{ .port_prefix }}30

    ### THESE BELOW ARE NORMAL PORTS FOR INTERNAL ROUTING

  - name: direct20005
    protocol: TCP
    port: 20005
    targetPort: 20005
    
  - name: direct20006
    protocol: TCP
    port: {{ .port_prefix }}06
    targetPort: 20006
    
  - name: direct-fwxserver-s
    protocol: TCP
    port: 20015
    targetPort: 20015
    
  - name: direct-fwxserver-a 
    protocol: TCP
    port: 20016
    targetPort: 20016
    
  - name: direct-fwserver-ssl
    protocol: TCP
    port: 20017
    targetPort: 20017

  selector:
    app: fwserver-{{ .name }}
{{- end}}

