{{- range .Values.servers }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fwserver-{{ .name }}
  labels:
    app: fwserver-{{ .name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fwserver-{{ .name }}
  template:
    metadata:
      labels:
        app: fwserver-{{ .name }}
    spec:
      containers:
      - name: mdm-server
        image: filewave/fwserver:{{ .version }}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "{{ .memoryGi }}Gi"
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo 127.0.0.1 {{ .host }} >> /etc/hosts && mkdir -p /etc/xdg/filewave && echo '[General]' > /etc/xdg/filewave/fwxserver.conf && echo 'vncRelayPort={{ .port_prefix }}30' >>/etc/xdg/filewave/fwxserver.conf && cp -rfL /tmp/secret/server.key /usr/local/filewave/certs/ && cp -rfL /tmp/secret/server.crt /usr/local/filewave/certs/"]
        livenessProbe: # restart services when this is REALLY BORKED 
          httpGet:
            path: /api/config/app
            port: 443
            scheme: HTTPS
          periodSeconds: 10         # once every 10 seconds
          timeoutSeconds: 5         # timeout if no reply in 5 seconds
          failureThreshold: 10      # failure after 10 attempts with no answer 
          initialDelaySeconds: 100  # dont check for the first 200 seconds after pod creation
        readinessProbe: # traffic to this pod is suspended when the probe fails
          httpGet:
            path: /api/config/app
            port: 443
            scheme: HTTPS
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
          - mountPath: "/usr/local/filewave/fwxserver/DB"
            name: ssd-vol-{{ .name }}
            subPath: db
          - mountPath: "/private/var/log/FWAdmin Audit"
            name: standard-vol-{{ .name }}
            subPath: audit
          - mountPath: "/usr/local/filewave/fwxserver/Data Folder"
            name: standard-vol-{{ .name }}
            subPath: data-folder
          - mountPath: "/usr/local/filewave/apache/conf"
            name: standard-vol-{{ .name }}
            subPath: apache-conf 
          - mountPath: "/usr/local/filewave/apache/logs"
            name: standard-vol-{{ .name }}
            subPath: apache-logs 
          - mountPath: "/usr/local/filewave/postgresql/conf"
            name: standard-vol-{{ .name }}
            subPath: postgres-conf
          - mountPath: "/usr/local/filewave/postgresql/log"
            name: standard-vol-{{ .name }}
            subPath: postgres-log
          - mountPath: "/usr/local/filewave/certs"
            name: standard-vol-{{ .name }}
            subPath: certs
          - mountPath: "/usr/local/filewave/fwcld"
            name: standard-vol-{{ .name }}
            subPath: fwcld
          - mountPath: "/usr/local/filewave/ipa"
            name: standard-vol-{{ .name }}
            subPath: ipa
          - mountPath: "/usr/local/filewave/log"
            name: standard-vol-{{ .name }}
            subPath: log
          - mountPath: "/usr/local/filewave/media"
            name: standard-vol-{{ .name }}
            subPath: media
          - mountPath: "/usr/local/filewave/tmp"
            name: standard-vol-{{ .name }}
            subPath: tmp
          - mountPath: "/usr/local/filewave/scripts"
            name: standard-vol-{{ .name }}
            subPath: scripts
          - mountPath: "/tmp/secret"
            name: cert-secret

        ports:
        - containerPort: 443
        - containerPort: {{ .port_prefix }}30
        - containerPort: 20015
        - containerPort: 20016
        - containerPort: 20017        
        - containerPort: 20013
        - containerPort: 20443
        - containerPort: 20445
        - containerPort: 20446
        - containerPort: 20448
        - containerPort: 20005
        - containerPort: 20006
        
      volumes:
      - name: standard-vol-{{ .name }}
        persistentVolumeClaim:
          claimName: fwserver-standard-{{ .name }}
      - name: ssd-vol-{{ .name }}
        persistentVolumeClaim:
          claimName: fwserver-ssd-{{ .name }}
      - name: cert-secret
        secret:
          secretName: default-cert
          items:
          - key: tls.key
            path: server.key #/tmp/secret/server.key cp /tmp/secret/server.key /
            mode: 0600
          - key: tls.crt
            path: server.crt
            mode: 0664
      imagePullSecrets:
        - name: regcred
{{- end}}
