{{- range .Values.clientsConfiguration }}
{{- if .enabled }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: {{ $.Values.environmentName }}-client-{{ .name }}
    labels:
        app: {{ $.Values.environmentName }}-client-{{ .name }}
spec:
    replicas: {{ .count }}
    selector:
        matchLabels:
            app: {{ $.Values.environmentName }}-client-{{ .name }}
    template:
        metadata:
            labels:
                app: {{ $.Values.environmentName }}-client-{{ .name }}
        spec:
            containers:
                - name: fwclient
                  image: "filewave/fwcld:{{ $.Values.clientVersion }}"
                  resources:
                      requests:
                          memory: "20Mi"
                  env:
                      - name: "FILEWAVE_SERVER_HOST"
                        value: "{{ $.Values.serverHostname }}"
                      - name: "FWCLD_SERVER_PORT"
                        value: "20015"
                      - name: "FWCLD_SERVER_PUB_PORT"
                        value: "20005"
                      - name: "FWCLD_CLIENT_NAME"
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
{{- if .upstreamBoosterHostname }}
                      - name: "FWCLD_BOOSTER1_HOST"
                        value: "{{ $.Values.environmentName }}-booster-{{ .upstreamBoosterHostname }}-svc"
                      - name: "FWCLD_BOOSTER1_PORT"
                        value: "20013"
                      - name: "FWCLD_BOOSTER1_PUB_PORT"
                        value: "20003"
{{- end }}
                  lifecycle:
                      postStart:
                          exec:
                              command: ["/bin/sh", "-c", "echo \"$(nslookup {{ $.Values.environmentName }}-server-svc | grep \"Name\" -A1 | grep \"Address\" | cut -d' ' -f2) {{ $.Values.serverHostname }}\" >> /etc/hosts"]
            imagePullSecrets:
                - name: regcred
{{- end }}
{{- end }}
