kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.environmentName }}-prom-standard-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.prometheusStorage }}
  storageClassName: standard
