{{- if and .Values.prometheusServiceEnabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.environmentName }}-prom-server-svc
spec:
  type: LoadBalancer
  ports:
    - name: prom-port
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: pushgateway
      protocol: TCP
      port: 9091
  selector:
    app: {{ .Values.environmentName }}-prometheus
{{- end }}
