{{- if and .Values.prometheus.serviceEnabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.prometheus.name }}-server-svc
spec:
  type: LoadBalancer
  ports:
    - name: prom-port
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: pushgateway
      protocol: TCP
      port: 9091
    # - name: grafana
    #   protocol: TCP
    #   port: 3000

  selector:
    app: {{ .Values.environmentName }}-prometheus
{{- end }}
