{{- if .Values.prometheusEnabled -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.environmentName }}-prometheus
  labels:
    app: {{ .Values.environmentName }}-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.environmentName }}-prometheus
  template:
    metadata:
      labels:
        app: {{ .Values.environmentName }}-prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.prometheusImageRepository }}:{{ .Values.prometheusImageTag }}
          imagePullPolicy: {{ .Values.prometheusImagePullPolicy }}
          args: 
            - --config.file=/etc/config/prometheus.yml
          resources:
            limits:
              cpu: {{ .Values.prometheusCpu }}
              memory: {{ .Values.prometheusMemory }}
          readinessProbe:
            httpGet:
              port: 9090
              scheme: HTTP
          ports:
              - containerPort: 9090
          volumeMounts:
            - name: config-vol
              mountPath: /etc/config
            - name: prometheus-vol-{{ .Release.Name }}
              mountPath: /data
              subPath: data
        - name: pushgateway
          image: {{ .Values.pushgatewayImageRepository }}:{{ .Values.pushgatewayImageTag }}
          imagePullPolicy: {{ .Values.pushgatewayImagePullPolicy }}
          readinessProbe:
            httpGet:
              port: 9091
              scheme: HTTP
          resources:
            limits:
              cpu: {{ .Values.pushgatewayCpu }}
              memory: {{ .Values.pushgatewayMemory }}
          ports:
            - containerPort: 9091
            - containerPort: 3000
      volumes:
        - name: prometheus-vol-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: {{ .Values.environmentName }}-prom-standard-pvc
        - name: config-vol
          configMap:
            name: {{ .Values.environmentName }}-prom-settings
            defaultMode: 0666


{{- end -}}