{{- if .Values.serverEnabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.environmentName }}-server
  labels:
    app: {{ .Values.environmentName }}-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.environmentName }}-server
  template:
    metadata:
      labels:
        app: {{ .Values.environmentName }}-server
    spec:
      containers:
        - name: fwserver
          image: "filewave/fwserver:{{ .Values.serverVersion }}"
          imagePullPolicy: Always
          resources:
            requests:
              cpu: {{ .Values.serverCpu }}
              memory: {{ .Values.serverMemory }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo 127.0.0.1 {{ .Values.serverHostname }} >> /etc/hosts && cp -rfL /tmp/secret/server.key /usr/local/filewave/certs/ && cp -rfL /tmp/secret/server.crt /usr/local/filewave/certs/"]
          readinessProbe:
            httpGet:
              path: /api/config/app
              port: 443
              scheme: HTTPS
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - mountPath: "/usr/local/filewave/fwxserver/DB"
              name: ssd-vol-{{ .Release.Name }}
              subPath: db
            - mountPath: "/private/var/log/FWAdmin Audit"
              name: standard-vol-{{ .Release.Name }}
              subPath: audit
            - mountPath: "/usr/local/filewave/fwxserver/Data Folder"
              name: standard-vol-{{ .Release.Name }}
              subPath: data-folder
            - mountPath: "/usr/local/filewave/apache/conf"
              name: standard-vol-{{ .Release.Name }}
              subPath: apache-conf
            - mountPath: "/usr/local/filewave/apache/logs"
              name: standard-vol-{{ .Release.Name }}
              subPath: apache-logs
            - mountPath: "/usr/local/filewave/postgresql/conf"
              name: standard-vol-{{ .Release.Name }}
              subPath: postgres-conf
            - mountPath: "/usr/local/filewave/postgresql/log"
              name: standard-vol-{{ .Release.Name }}
              subPath: postgres-log
            - mountPath: "/usr/local/filewave/certs"
              name: standard-vol-{{ .Release.Name }}
              subPath: certs
            - mountPath: "/usr/local/filewave/fwcld"
              name: standard-vol-{{ .Release.Name }}
              subPath: fwcld
            - mountPath: "/usr/local/filewave/ipa"
              name: standard-vol-{{ .Release.Name }}
              subPath: ipa
            - mountPath: "/usr/local/filewave/log"
              name: standard-vol-{{ .Release.Name }}
              subPath: log
            - mountPath: "/usr/local/filewave/media"
              name: standard-vol-{{ .Release.Name }}
              subPath: media
            - mountPath: "/usr/local/filewave/tmp"
              name: standard-vol-{{ .Release.Name }}
              subPath: tmp
            - mountPath: "/usr/local/filewave/scripts"
              name: standard-vol-{{ .Release.Name }}
              subPath: scripts
            - mountPath: "/tmp/secret"
              name: cert-secret
{{- if not .Values.serverSoftwareUpdateProcessEnabled }}
            - mountPath: "/root/.config/filewave/"
              name: disable-fwsu-server-settings
{{- end }}
          ports:
            - containerPort: 443
            - containerPort: 20005
            - containerPort: 20006
            - containerPort: 20013
            - containerPort: 20015
            - containerPort: 20016
            - containerPort: 20017
            - containerPort: 20019
            - containerPort: 20030
            - containerPort: 20443
            - containerPort: 20445
            - containerPort: 20446
            - containerPort: 20448
      volumes:
        - name: standard-vol-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: {{ .Values.environmentName }}-standard-pvc
        - name: ssd-vol-{{ .Release.Name }}
          persistentVolumeClaim:
            claimName: {{ .Values.environmentName }}-ssd-pvc
        - name: cert-secret
          secret:
            secretName: default-cert
            items:
              - key: tls.key
                path: server.key
                mode: 0600
              - key: tls.crt
                path: server.crt
                mode: 0664
{{- if not .Values.serverSoftwareUpdateProcessEnabled }}
        - name: disable-fwsu-server-settings
          configMap:
            name: {{ .Values.environmentName }}-disable-fwsu-server-settings
            defaultMode: 0666
{{- end }}
      imagePullSecrets:
        - name: regcred
{{- end }}
